# ./postgres.configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: kube-config-postgres
  labels:
    feature: "databases"
data:
  POSTGRES_HOST: "192.168.0.1"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "poll_db"