# ./postgres.configmap.yaml
apiVersion: apps/v1
kind: ConfigMap
metadata:
  namespace: default
  name: kube-config-postgres
  labels:
    feature: "databases"
data:
  POSTGRES_HOST: kube-service-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "poll_db"