# ./postgres.configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: kube-config-postgres
  labels:
    databases: postgres
data:
  POSTGRES_HOST: kube-service-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "poll_db"