# ./traefik.deployment.yaml

# https://doc.traefik.io/traefik/v1.7/user-guide/kubernetes/#deploy-traefik-using-a-deployment-or-daemonset

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-serviceacc-traefik
  namespace: kube-public

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-serviceacc-traefik
  namespace: kube-public
  labels:
    k8s-app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik
  template:
    metadata:
      labels:
        k8s-app: traefik
        name: traefik-ingress
    spec:
      containers:
        - name: traefik
          image: traefik:2.7
          ports:
            - name: http
              containerPort: 80
            - name: admin
              containerPort: 8080
          args:
          - --api
          - --kubernetes
          - --logLevel=INFO
      serviceAccountName: kube-serviceacc-traefik
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8a-app
                operator: In
                values:
                - traefik
            topologyKey: "kubernetes.io/hostname"
