# ./traefik.deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-serviceacc-traefik
  namespace: kube-public
  labels:
      app: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-public
  name: kube-deploy-traefik